apiVersion: v1
kind: ConfigMap
metadata:
  name: safepath-config
  namespace: safepath
  labels:
    app.kubernetes.io/name: cot-safepath-filter
    app.kubernetes.io/component: config
data:
  # Application configuration
  LOG_LEVEL: "INFO"
  ENVIRONMENT: "production"
  
  # Self-healing configuration
  SELF_HEALING_ENABLED: "true"
  MONITORING_INTERVAL: "30"
  HEALING_COOLDOWN_MINUTES: "5"
  MAX_HEALING_ATTEMPTS: "3"
  
  # Performance optimization
  PERFORMANCE_OPTIMIZATION_ENABLED: "true"
  OPTIMIZATION_STRATEGY: "adaptive"
  AUTO_SCALING_ENABLED: "true"
  CACHE_SIZE_MB: "100"
  
  # Security configuration
  SECURITY_HARDENING_ENABLED: "true"
  RATE_LIMITING_ENABLED: "true"
  MAX_REQUESTS_PER_MINUTE: "60"
  MAX_REQUESTS_PER_HOUR: "1000"
  
  # Monitoring configuration
  METRICS_ENABLED: "true"
  METRICS_PORT: "9090"
  HEALTH_CHECK_INTERVAL: "30"
  
  # Database configuration
  DB_CONNECTION_POOL_SIZE: "10"
  DB_CONNECTION_TIMEOUT: "30"
  
  # Redis configuration
  REDIS_CONNECTION_POOL_SIZE: "10"
  REDIS_CONNECTION_TIMEOUT: "5"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: safepath-filter-config
  namespace: safepath
  labels:
    app.kubernetes.io/name: cot-safepath-filter
    app.kubernetes.io/component: filter-config
data:
  filter_config.yaml: |
    safety_levels:
      strict:
        filter_threshold: 0.8
        enable_all_detectors: true
        block_categories:
          - violence
          - illegal_activity
          - deception
          - harmful_advice
          - manipulation
        
      balanced:
        filter_threshold: 0.6
        enable_all_detectors: true
        block_categories:
          - violence
          - illegal_activity
          - deception
        
      permissive:
        filter_threshold: 0.3
        enable_basic_detectors: true
        block_categories:
          - extreme_violence
          - illegal_activity
    
    detectors:
      deception_detector:
        enabled: true
        confidence_threshold: 0.7
        model: "bert-base-uncased"
        
      harmful_planning_detector:
        enabled: true
        confidence_threshold: 0.8
        pattern_matching: true
        
      security_threat_detector:
        enabled: true
        confidence_threshold: 0.9
        real_time_analysis: true
        
      prompt_injection_detector:
        enabled: true
        confidence_threshold: 0.8
        advanced_patterns: true
    
    performance:
      caching:
        enabled: true
        policy: "intelligent"
        max_size_mb: 100
        ttl_seconds: 3600
        
      concurrent_processing:
        enabled: true
        worker_pool_size: 4
        max_worker_pools: 8
        load_balancing_strategy: "adaptive"
        
      optimization:
        enabled: true
        strategy: "adaptive"
        auto_scaling: true
        resource_monitoring: true