apiVersion: v1
kind: Service
metadata:
  name: safepath-filter-service
  namespace: safepath
  labels:
    app.kubernetes.io/name: cot-safepath-filter
    app.kubernetes.io/component: service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: metrics
    protocol: TCP
  selector:
    app.kubernetes.io/name: cot-safepath-filter
    app.kubernetes.io/component: filter

---
apiVersion: v1
kind: Service
metadata:
  name: safepath-filter-headless
  namespace: safepath
  labels:
    app.kubernetes.io/name: cot-safepath-filter
    app.kubernetes.io/component: headless-service
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  selector:
    app.kubernetes.io/name: cot-safepath-filter
    app.kubernetes.io/component: filter

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: safepath-filter-ingress
  namespace: safepath
  labels:
    app.kubernetes.io/name: cot-safepath-filter
    app.kubernetes.io/component: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "30"
    nginx.ingress.kubernetes.io/rate-limit-connections: "100"
    nginx.ingress.kubernetes.io/rate-limit-rps: "50"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - safepath.terragonlabs.com
    secretName: safepath-tls
  rules:
  - host: safepath.terragonlabs.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: safepath-filter-service
            port:
              number: 80